from __future__ import annotations

import logging
import secrets
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)

GLITCH_HOME = Path.home() / ".glitch"
CONFIG_DIR = GLITCH_HOME
ENV_FILE = GLITCH_HOME / ".env"

# The app's own git repo — what the self-modification flow edits. Defaults to the
# repository that contains this package (parent of the `glitch_core/` dir).
DEFAULT_REPO_ROOT = Path(__file__).resolve().parent.parent


class GlitchEnv(BaseSettings):
    """Machine-local environment, read from ~/.glitch/.env (prefix GLITCH_)."""

    model_config = SettingsConfigDict(
        env_prefix="GLITCH_",
        env_file=str(ENV_FILE),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Model auth is handled by the `claude` CLI directly (claude.ai login, or a
    # raw ANTHROPIC_API_KEY in the environment). Glitch does not manage it.

    # Single-user auth.
    admin_username: str = "admin"
    admin_password_hash: str = ""  # bcrypt hash; set by `glitch bootstrap`
    admin_password: str | None = None  # dev convenience: plaintext, hashed at runtime
    session_secret: str = ""  # stable across restarts; generated by bootstrap

    # Persistence + self-mod target.
    db_path: Path = GLITCH_HOME / "glitch.db"
    repo_root: Path = DEFAULT_REPO_ROOT

    # Web server.
    host: str = "127.0.0.1"
    port: int = 8080

    # Timezone for scheduled tasks (e.g. the PM 10am nudge). IANA name, e.g. "America/New_York".
    tz: str = "UTC"

    def effective_session_secret(self) -> str:
        """Return a stable session secret, persisting a generated one if unset.

        Sessions must survive the app restarts triggered by self-modification,
        so the secret cannot be ephemeral. Bootstrap normally writes one into
        ~/.glitch/.env; this is the fallback for dev runs without bootstrap.
        """
        if self.session_secret:
            return self.session_secret
        secret_file = GLITCH_HOME / "session_secret"
        if secret_file.exists():
            return secret_file.read_text().strip()
        GLITCH_HOME.mkdir(parents=True, exist_ok=True)
        value = secrets.token_urlsafe(48)
        secret_file.write_text(value)
        logger.warning("Generated an ephemeral session secret at %s", secret_file)
        return value
