from __future__ import annotations

import logging
import secrets
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)

POIESIS_HOME = Path.home() / ".poiesis"
CONFIG_DIR = POIESIS_HOME
ENV_FILE = POIESIS_HOME / ".env"

# The app's own git repo — what the self-modification flow edits. Defaults to the
# repository that contains this package (parent of the `poiesis/` dir).
DEFAULT_REPO_ROOT = Path(__file__).resolve().parent.parent


class PoiesisEnv(BaseSettings):
    """Machine-local environment, read from ~/.poiesis/.env (prefix POIESIS_)."""

    model_config = SettingsConfigDict(
        env_prefix="POIESIS_",
        env_file=str(ENV_FILE),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Model auth is handled by the `claude` CLI directly (claude.ai login, or a
    # raw ANTHROPIC_API_KEY in the environment). Poiesis does not manage it.

    # Single-user auth.
    admin_username: str = "admin"
    admin_password_hash: str = ""  # bcrypt hash; set by `poiesis bootstrap`
    admin_password: str | None = None  # dev convenience: plaintext, hashed at runtime
    session_secret: str = ""  # stable across restarts; generated by bootstrap

    # Persistence + self-mod target.
    db_path: Path = POIESIS_HOME / "poiesis.db"
    repo_root: Path = DEFAULT_REPO_ROOT

    # Web server.
    host: str = "127.0.0.1"
    port: int = 8080

    # Timezone for scheduled tasks (e.g. the PM 10am nudge). IANA name, e.g. "America/New_York".
    tz: str = "UTC"

    # #spice: an OpenAI-compatible provider (Featherless by default), used instead of
    # the Claude Agent SDK for that one channel. Key goes in ~/.poiesis/.env.
    spice_api_key: str = ""
    spice_base_url: str = "https://api.featherless.ai/v1"
    spice_model: str = "dphn/Dolphin-Mistral-24B-Venice-Edition"  # POIESIS_SPICE_MODEL overrides
    # Default endpoint for #spice's `fetch` tool when called without a url — the
    # challenges JSON. Naive GET for now (CF Access lets the server's own IP through);
    # add a token seam here if that changes.
    spice_challenges_url: str = ""

    def effective_session_secret(self) -> str:
        """Return a stable session secret, persisting a generated one if unset.

        Sessions must survive the app restarts triggered by self-modification,
        so the secret cannot be ephemeral. Bootstrap normally writes one into
        ~/.poiesis/.env; this is the fallback for dev runs without bootstrap.
        """
        if self.session_secret:
            return self.session_secret
        secret_file = POIESIS_HOME / "session_secret"
        if secret_file.exists():
            return secret_file.read_text().strip()
        POIESIS_HOME.mkdir(parents=True, exist_ok=True)
        value = secrets.token_urlsafe(48)
        secret_file.write_text(value)
        logger.warning("Generated an ephemeral session secret at %s", secret_file)
        return value
